import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";


export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // optional, for CSS variable
});

export const metadata: Metadata = {
  title: "Ink n Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
